=== hearwindcry/xml-xml2sql/src/main/resources/db-define-meta.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT databases (database+)>
<!ELEMENT database (table+)>
<!ATTLIST database
        name CDATA #REQUIRED
        encoding CDATA #IMPLIED>

<!ELEMENT table (field+)>
<!ATTLIST table
        name CDATA #REQUIRED
        engine CDATA #REQUIRED
        charset CDATA #REQUIRED
        collate CDATA #REQUIRED>

<!ELEMENT field EMPTY>
<!ATTLIST field
        name CDATA #REQUIRED
        type CDATA #REQUIRED
        nullable (true|false) #REQUIRED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED>

=== hearwindcry/xml-xml2sql/src/main/resources/mydbdefine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE databases SYSTEM "db-define-meta.dtd">
<databases>
    <database name="db1" encoding="UTF-8">
        <table name="tb_hello" engine="InnoDB" charset="utf8mb4" collate ="utf8mb4_general_ci">
            <field name="id" type="int" nullable="false"/>
            <field name="name" type="varchar(20)" nullable="false" default=""/>
            <field name="other" type="text" nullable="false" default=""/>
        </table>
    </database>

    <database name="db2" encoding="UTF-8">
        <table name="tb_goodnight" engine="InnoDB" charset="utf8mb4" collate ="utf8mb4_general_ci">
            <field name="id" type="int" nullable="false"/>
            <field name="time" type="datetime" nullable="false"/>
        </table>
    </database>
</databases>
